services:
    type: web
    name: library-management_
    env: python
    buildCommand: ""
    startCommand: "gunicorn app:app"
    envVars:
        key: DATABASE_URL
        value: mysql+pymysql://username:password@host:3306/database_name
